# NUMPY(Numerical python)

Numpy:

--- Used for working of arrays

--- In python we have lists that serve the purpose of arrays,but they are slow to process

--- Numpy is incredible library to perform mathematical and statistical operations due to its fast and memory efficient as it is optimized to work with latest CPU architectures

--- Numpy aims to provide an array object that is upto 50x faster than traditional python lists.So processes can access and
     manipulate them very efficiently

# in easyway
       
       Numpy is numerical python where it is used to work in terms of numerical data and mathematical operations 

# difference between nparray and list----------
            
    Numpy-----arrays
    python---- we have list to serve the purpose of arrays,but they are slow

In [9]:
a=[1,2,3,4,5]            # here in python,the output is list of array and type of list
print(a)
type(a)

[1, 2, 3, 4, 5]


list

In [1]:
#in numpy
import numpy as np    # here we are importing numpy as np 
a=[1,2,3,4,5]
np_a=np.array(a)      # converting the list of array as np.array(ahow to convert)
print(np_a)
type(np_a)
    

[1 2 3 4 5]


numpy.ndarray

How to convert list to array-----
            
            np.array()   # is a function available in numpy module

while printing the output the difference between list and numpy is----
   
            list----[1,2,3,4,5]
           numpy----[1 2 3 4 5]   #comma is not there

In [14]:
l1=[1,2,3]                                         
l=[]                                                
for i in range(len(l1)):                            
    a=l1[i]+10                                        
    l.append(a)                                        
print(l)                                                

[11, 12, 13]


In [15]:
l1=[1,2,3]
l=[]
for i in l1:
    a=i+10
    l.append(a)
print(l)

[11, 12, 13]


In [ ]:
# the above code is for python but in numpy-----

In [16]:
l1=[1,2,3]
np.array(l1)+10     # by default,in backend the for loop is applicable for     np.array(l1)+10

array([11, 12, 13])

In [17]:
# list comprehension(in core python)

l1=[1,2,3]
for i in l1:
    print(i)

1
2
3


In [19]:
l=[]
for i in l1:
    l.append(i)
print(l)
    

[1, 2, 3]


In [20]:
# in numpy
l=[]
[i for i in l1]     # whatever we want to append write in first position in for loop

[1, 2, 3]

In [21]:
# for adding 10    whatever we want to add,first we write the appending and then for loop
[i+10 for i in l1]    # by default in backend for loop for i+10 is done

[11, 12, 13]

In [23]:
# input is l1=[1,2,3] and l2=[4,5,6] and output is l=[5,7,9] what is code?
l1=[1,2,3]
l2=[4,5,6]
l=[]
for i in range (3):
    a = l1[i]+l2[i]
    l.append(a)
print(l)

[5, 7, 9]


In [9]:
import numpy as np
np.array(l1)
np.array(l2)
l1=[1,2,3]
l2=[4,5,6]
np.array(l1)+np.array(l2)

array([5, 7, 9])

# Numpy Arrays

# 0-D:(0-dimension)
       
           means a single value
      
    

In [12]:
a=45
arr_0=np.array(a)      #arr_0 is variable name
print(arr_0)
type(arr_0)

45


numpy.ndarray

In [13]:
arr_0.ndim

0

In [14]:
arr_0.shape     #if the output is empty it is o-dimension

()

# 1-D:(1-dimension)
       
      minimum it should be list
    

In [20]:
a=[45]
arr1=np.array(a)
print(arr1)
type(arr1)

[45]


numpy.ndarray

In [21]:
arr1.ndim


1

In [22]:
arr1.shape         (1,) means 1 dimensional

(1,)

# 2-D(2-dimension):   (no of rows,no of columns)
            
          A combination of two 1-dimensions

In [25]:
a=[[1,2,3],[4,5,6]]
arr2=np.array(a)
print(arr2)
type(arr2)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [26]:
arr2.ndim

2

In [27]:
arr2.shape

(2, 3)

In [28]:
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [29]:
print(a)           # here the output is [0 1 2 3]with no commas ,we can identify as a list

[0 1 2 3]


In [30]:
a.ndim

1

In [31]:
a.shape

(4,)

In [32]:
arr=np.array("subha")
print(arr)

subha


In [33]:
type(arr)

numpy.ndarray

In [34]:
arr.ndim

0

In [38]:
a1=[1,2,3]
arr1=np.array(a1)
print(arr1)

[1 2 3]


In [39]:
arr1.ndim

1

In [40]:
arr1.shape

(3,)

In [3]:
import numpy as np
a2=[[1,2,3]]        # if no brackets are there 0-d,1 bracket-1d,2 brackets-2d
arr2=np.array(a2)
print(arr2)

[[1 2 3]]


In [4]:
arr2.ndim

2

In [5]:
arr2.shape

(1, 3)

# Functions for creating 1D array
          
    


arange: is an array_valued version of the built -in python range fn
    
    syntax:np.arange(start,end,step)

In [3]:
import numpy as np
a=np.arange(10,110,10)    #it converts into normal range fn without commas
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


linspace: return evenly spaced numbers over a specified interval
     
        syntax: np.linspace(start,end,no of samples)

In [4]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [5]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

Zeros: Generates arrays of zeros
    
    syntax : np.zeros(shape)

In [6]:
np.zeros((3,))

array([0., 0., 0.])

Ones: generates arrays of ones
   
        syntax :np.ones(shape)
    

In [7]:
np.ones((3,))

array([1., 1., 1.])

np.zeros()--------only 0's

np.ones()---------only 1's

but we want 2's mean

In [10]:
np.zeros((3,))+2

array([2., 2., 2.])

they created zeros and ones only ---
     
    in numpy array matrices are used
    

In [ ]:
zero matrix   [0 0]                    unity matrix     [1 1]
               
               [0 0]                                     [1 1]

by default it takes float value ---[0.,0.,]  or [1.,1.,]

if we want in int----


In [11]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

# random.randint
       
        return random integers from start(inclusive) to end (exclusive)
    
       syntax  is---- np.random.randint(start,end,no of samples)

In [15]:
np.random.randint(1,41,5)

array([13, 40, 36, 28, 14])

# Accessing elements/extracting the value
 
1.Accessing a single value through Indexing

2.Accessing a multiple values based on slicing

3.Accessing a multiple values based on indexing

4.Accessing a multiple values based on condition

In [2]:
import numpy as np
a=np.arange(10,51,10)
print(a)


[10 20 30 40 50]


1.accessing a single value through indexing



In [3]:
a[1]    #positive indexing

20

In [4]:
a[-1]    # negative indexing

50

In [5]:
a[1.5]     # index cant be in float

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

2.accessing a multiple values based on slicing


In [6]:
a[1:5:2]

array([20, 40])

In [7]:
a[-1:-4]        # here SP is -4 and Ep is -1 but increment is 1 it gives noting so it empty array[]

array([], dtype=int32)

In [8]:
a[-4:4]

array([20, 30, 40])

3.accessing a multiple values based on indexing
     
      syntax : array[(list of index numbers)]

In [6]:
l=[10,20,30,40,50]
a=np.array(l)
a[[0,3,4]]

array([10, 40, 50])

In [13]:
l=[10,10,10,20,40,10,40,30,50]
a=np.array(l)
a[[0,0,0,1,3,0,3,2,4]]

array([10, 10, 10, 10, 20, 10, 20, 10, 40])

In [8]:
a[[0,4,6,5,4]]

IndexError: index 6 is out of bounds for axis 0 with size 5

4.accessing a multiple values based on condition(Mask indexing or Fancy indexing)

                           
                     syntax:array[condition]  (first,it will check the condition the item or value which satisfies the 
                                        condition(means which item gives True for the condition)that item will be selected)

What is meant by NUMPY array?
     
       first it create empty list a[]
          then forloop for()
            then append a.append()

code for index no in core python is___________
              
              a[0,0,0,1,3,0,3,2,4]
              index=[0,0,0,1,3,0,3,2,4]
              l=[]
              for i in index:
              l.append(a[index])
              


MODIFY THE VALUES IN NUMPY:

ADD A SINGLE VALUE IN A ARRAY____________
          
           SYNTAX : np.append(array,value)

In [7]:
import numpy as np
l=[10,4,1,3,4]
a=np.array(l)
a


array([10,  4,  1,  3,  4])

In [8]:
np.append(a,110)

array([ 10,   4,   1,   3,   4, 110])

ADD  MULTIPLE  VALUES  IN  A  ARRAY

In [16]:
np.append(a,[110,120,130])     #without storing 'a' in single values


array([ 10,   4,   1,   3,   4, 110, 120, 130])

In [21]:
#AFTER STORING THE ARRAY INTO 'a' THE OUTPUT IS__________

a=np.append(a,110)
a

array([ 10,   4,   1,   3,   4, 110, 110, 110, 110, 110])

In [22]:
np.append(a,[110,120,130])

array([ 10,   4,   1,   3,   4, 110, 110, 110, 110, 110, 110, 120, 130])

REPLACE A SINGLE VALUE IN A 1D-ARRAY

In [3]:
import numpy as np
l=[10,4,1,3,4,110]
a=np.array(l)
a

array([ 10,   4,   1,   3,   4, 110])

In [4]:
a[0]=150                # adding 150 at index 0
print(a)

[150   4   1   3   4 110]


Replace multiple values with a single value in a array

In [5]:
a[[1,4]]=800          # replace 1 and 4 index positions values with 800
a

array([150, 800,   1,   3, 800, 110])

In [6]:
a[[2,5]]=200
a

array([150, 800, 200,   3, 800, 200])

REPLACING A MULTIPLE VALUES WITH A MULTIPLE VALUES IN A ARRAY

In [7]:
a[[1,4]]=[10,4]
a


array([150,  10, 200,   3,   4, 200])

DELETE A SINGLE VALUE IN A ARRAY

In [8]:
np.delete(a,1)          #  a-array,1-index no

array([150, 200,   3,   4, 200])

DELETE MULTIPLE VALUES IN A ARRAY

In [9]:
a

array([150,  10, 200,   3,   4, 200])

In [10]:
np.delete(a,[1,2])      

array([150,   3,   4, 200])

# copy array

In [11]:
a=np.array([1,2,3])
b=a.copy()                  # this is a shallow copy
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [12]:
a=np.array([1,2,3])
b=a
b[0]=100                # this is a deep copy
print(a)
print(b)

[100   2   3]
[100   2   3]


# sorting an array
    
           By default ascending order,if we want descending order----np.reverse=True

In [13]:
np.sort([4,6,8,2,1])

array([1, 2, 4, 6, 8])

# Arithmetic operations

In [14]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [15]:
a+1

array([2, 3, 4, 5])

In [16]:
a**2

array([ 1,  4,  9, 16])

In [17]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(a)
print(b)
print(c)

[1 2 3 4]
[5 6 7 8]
[1 2 3 4]


In [18]:
a+b


array([ 6,  8, 10, 12])

In [19]:
a-b

array([-4, -4, -4, -4])

In [20]:
a*b

array([ 5, 12, 21, 32])

# Comparision operators

In [21]:
a==b

array([False, False, False, False])

In [22]:
a==c

array([ True,  True,  True,  True])

if we want to get values_______

In [23]:
a[a==c]

array([1, 2, 3, 4])

In [33]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,5,4])
print(a)
print(b)
print(c)

[1 2 3 4]
[5 6 7 8]
[1 2 5 4]


In [25]:
a[a==c]                # it gives true values

array([1, 2, 4])

In [26]:
a>b

array([False, False, False, False])

In [36]:
np.array_equal(a,b)

False

In [37]:
np.array_equal(a,c)

False

# Mathematical operations

In [38]:
a=np.arange(0,6)
a

array([0, 1, 2, 3, 4, 5])

In [39]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [40]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [45]:
import warnings
warnings.simplefilter("ignore")
np.log(a)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])

# 2D Numpy Array  

In [46]:
b=np.array([[0,1,2]]) 
print(b)

[[0 1 2]]


In [47]:
b.ndim

2

In [48]:
b.shape

(1, 3)

In [49]:
np.zeros((3,3))         # 2D array with 3 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

BY DEFAULT IT TAKES FLOAT VALUES,IF WE WANT INT VALUES MEANS WE HAVE TO GIVE dtype=int

In [83]:
print(np.zeros((3,3),dtype=int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [54]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [57]:
print(np.ones((3,2),dtype=int))

[[1 1]
 [1 1]
 [1 1]]


# Identity Matrix

In [81]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [80]:
print(np.eye(3,2,dtype=int))

[[1 0]
 [0 1]
 [0 0]]


# Diagonal matrix

In [61]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [62]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [64]:
a=np.array([[1,2],[0,4]])
a

array([[1, 2],
       [0, 4]])

In [65]:
np.array([[1,2],[0,4]])

array([[1, 2],
       [0, 4]])

In [66]:
np.diag(a)      # it extracts the diagonal values

array([1, 4])

In np.diag,input is 1D the output is 2D
  
    np.diag,input is 2D the output is 1D

In [67]:
a=np.array([[10,20,50],[30,40,60]])
print(a)

[[10 20 50]
 [30 40 60]]


Indexing of 2D array

In [68]:
a[0]

array([10, 20, 50])

In [69]:
a[1]

array([30, 40, 60])

In [70]:
a[0,2]

50

In [71]:
a[:,2]

array([50, 60])

In [2]:
import numpy as np
a=np.array([[10,20,50],[30,40,60],[20,80,90]])
print(a)

[[10 20 50]
 [30 40 60]
 [20 80 90]]


In [3]:
a[0:2,2]         # 0:2 means 0 to2 rows i.e,0,1  

array([50, 60])

In [74]:
a[0:2,]         # 0 to 2 rows i.e 0,1 are rows and column no is not mentioned means it gives entire rows

array([[10, 20, 50],
       [30, 40, 60]])

In [4]:
a[1]

array([30, 40, 60])

In [5]:
a[0,2]

50

In [6]:
a[:,2]                # all columns values with indexing 2 i.e a[row indexing:,column indexing]

array([50, 60, 90])

In [7]:
a=np.array([[10,20,50],[30,40,60],[20,80,90]])
print(a)

[[10 20 50]
 [30 40 60]
 [20 80 90]]


In [8]:
a[0,2]                 # a[row index,column index] i.e 0th row 2nd column value

50

In [9]:
a[0:2,2]              # 0:2--- means 0 to 2 rows i.e 0 and 1 row and 2 is 2nd column values

array([50, 60])

In [10]:
a[0:2,]         # 0 to 2 rows i.e 0 and 1 rows and column no is not mentioned it means entire rows

array([[10, 20, 50],
       [30, 40, 60]])

In [11]:
a[[0,2],[0,1]]

array([10, 80])

 a[0,2]---------[10,20,50]
                [20,80,90]
        
 a[0,1]---------[10,20,50]
                [30,40,60]
        
        
        but output we get is [10,80]    but manually we got the output as [10,20]
                                                                           [20,80]
            
            here ,for numpy multiple rows and columns are not applicable so it is disadvantage
            so we go for PANDAS

ASSIGNING VALUE IN 2D ARRAY

In [12]:
a[1]=[25,30,60]             # here,we are replacing the 1st row with [25,30,60]
a

array([[10, 20, 50],
       [25, 30, 60],
       [20, 80, 90]])

In [13]:
a[0,2]=500                  # value of 0th row 2nd column is changed to 500
a

array([[ 10,  20, 500],
       [ 25,  30,  60],
       [ 20,  80,  90]])

# Flattening
            
          Converting nd array to 1d array

In [14]:
a=np.array([[0,1,2],[3,4,5]])
print(a)
b=a.ravel()              # ravel() is the fn name
print(b)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


# Reshape array

In [15]:
arr=np.arange(6)
print(arr)
print(arr.shape)

[0 1 2 3 4 5]
(6,)


In [16]:
a1=arr.reshape(2,3)       # it converts the above 6D into 2 rows and 3 columns
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
a2=arr.reshape(3,2)
a2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [19]:
a=np.array([[0,1,5],[10,50,8]])
print(a)
print(a.shape)

[[ 0  1  5]
 [10 50  8]]
(2, 3)


In [20]:
a.reshape(3,2)

array([[ 0,  1],
       [ 5, 10],
       [50,  8]])

earlier the data is (2,3),it has converted into 1D and then to our required shape [0 1 5 10 50 8]---> [[0,1],
                                                                                                          [5,10],
                                                                                                        [50.8]]
                                                                                 

   Instead of that ,we can write in another form by using Transpose
  
     Transpose converts rows-->columns
                        columns--->rows

In [21]:
c=a.T
print(c)

[[ 0 10]
 [ 1 50]
 [ 5  8]]


In [22]:
 print(a.reshape(6,1))

[[ 0]
 [ 1]
 [ 5]
 [10]
 [50]
 [ 8]]


In [4]:
import numpy as np
a=np.array(10)
a.ndim

0

 here single value is there,so it is 0D.if we want 1D means ,it is a combination of 0D,that we write in list

In [5]:
a=np.array([10,20])
a.ndim

1

2D-Nestedlist i.e a=[[1,2,3],[4,5,6]]

combinations of 1D gives 2D

# Sort
           
           sorting along axis
           
           in NUMPY   axis=0------>column wise
                      axis=1------>row wise

In [2]:
import numpy as np
a=np.array([[5,4,6],[2,8,2],[8,9,20]])
b=np.sort(a,axis=1)                    #axis=1 (row wise)
b

array([[ 4,  5,  6],
       [ 2,  2,  8],
       [ 8,  9, 20]])

In [3]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[4,4],[4,4],[4,4]])
print(a+b)

[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [4]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a*b)

[[ 5 12]
 [21 32]]


In [6]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.matmul(a,b)                # matrix multiplication

array([[19, 22],
       [43, 50]])

In [7]:
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


In [8]:
np.concatenate((a,b),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [10, 20],
       [30, 40]])

Columnwise concatenation or Vertical stacking

In [9]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [10, 20],
       [30, 40]])

Rowwise concatenation or Horizontal stacking

In [10]:
np.stack((a,b))                    # equal to np.concatenate((a,b),axis=1)

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 20],
        [30, 40]]])